### ISSUE TITLE
Confusing parameter in openssl command

### ISSUE THREAD

**Issue by davidlind** [sivasamyk/graylog2-input-lumberjack#3]
openssl pkcs12 -export -in lumberjack.crt -inkey lumberjack.key -out lumberjack.p12 -name localhost -passin pass:<password> -passout pass:<store-pass>

The parameter -name needs to have the servername provided for CN in the previous command, otherwise the following keystore command fails. "localhost" is confusing.

Perhaps this would be better:

openssl pkcs12 -export -in lumberjack.crt -inkey lumberjack.key -out lumberjack.p12 -name <graylog-server-name> -passin pass:<password> -passout pass:<store-pass>

**Comment by sivasamyk** [comment]
Updated the Readme.md file accordingly.
