### ISSUE TITLE
Receiving same messages again and again from Logstash-Forwarder

### ISSUE THREAD

**Issue by rcord02** [sivasamyk/graylog2-input-lumberjack#4]
Hi,
nice you have done this plugin. This is exactly what i was looking for to simplify my setup.
I've just tried it, setting up a connection between the (existing) logstash-forwarders and the graylog-server was straight forward. But it looks like the graylog server receives the same messages from the logstash-fowarder again and again (the amount of messages seems to be correct). 

I have a couple logstash-forwarder clients that have pushed the messages from file to the central logstash instance. The central logstash did the parsing (timestamps, fields etc.) and sent them to graylog. After shutting down the logstash, i have opened the graylog input for lumberjack on the same port (same server as well) . Receiving the messages started immediately but it looks like the forwarders are sending the old messages over and over again and none of the newer ones.
Maybe there is an issue in confirming the receiving of the messages on part of the input plugin.
Have you an idea what's wrong?
Versions:
logstash-fowarder 0.4.0
Graylog-server 1.1.6

**Comment by sivasamyk** [comment]
Can you paste the output of logstash forwarder in non-quiet mode (make sure you change the certs and other sensitive info)? It will log a message for every batch of events (max of 1024 events) sent to server in syslog or stdout based on configuration. Also check if there are any exceptions in graylog server log.

Are you seeing the same message being indexed  repeatedly in graylog?

**Comment by rcord02** [comment]
Thanks for your quick reply! The bunch of messages being repeatly indexed by graylog/elasticsearch are availible by the graylog gui. The graylog server does not throw any exceptions. 

Here is the log output from logstash-forwarder when sending to graylog (ServerName01 is the graylog machine running the input):

2015/09/30 08:52:25.823158 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:52:25.825267 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused
2015/09/30 08:52:26.828427 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:52:26.830497 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused
2015/09/30 08:52:27.833139 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:52:27.835351 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused
2015/09/30 08:52:28.838190 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:52:28.840211 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused
2015/09/30 08:52:29.843067 Connecting to [XX.XX.XX.XXX]:12210 (ServerName01)
2015/09/30 08:52:29.928294 Connected to XX.XX.XX.XXX
2015/09/30 08:52:44.928587 Read error looking for ack: read tcp XX.XX.XX.XXX:12210: i/o timeout
2015/09/30 08:52:44.928741 Setting trusted CA from file: /opt/graylog-agent/server-wildcard.crt
2015/09/30 08:52:44.931485 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:52:44.933560 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused
2015/09/30 08:52:45.936465 Connecting to [XX.XX.XX.XXX]:12210 (ServerName01)
2015/09/30 08:52:46.020301 Connected to XX.XX.XX.XXX
2015/09/30 08:53:01.020692 Read error looking for ack: read tcp XX.XX.XX.XXX:12210: i/o timeout
2015/09/30 08:53:01.020815 Setting trusted CA from file: /opt/graylog-agent/server-wildcard.crt
2015/09/30 08:53:01.023706 Connecting to [XX.XX.XX.XXX]:12210 (ServerName01)
2015/09/30 08:53:01.104396 Connected to XX.XX.XX.XXX
2015/09/30 08:53:16.104800 Read error looking for ack: read tcp XX.XX.XX.XXX:12210: i/o timeout
2015/09/30 08:53:16.104927 Setting trusted CA from file: /opt/graylog-agent/server-wildcard.crt
2015/09/30 08:53:16.107788 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:53:16.109834 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused
2015/09/30 08:53:17.112646 Connecting to [XX.XX.XX.XXX]:12210 (ServerName01)
2015/09/30 08:53:17.200417 Connected to XX.XX.XX.XXX
2015/09/30 08:53:32.200707 Read error looking for ack: read tcp XX.XX.XX.XXX:12210: i/o timeout
2015/09/30 08:53:32.200819 Setting trusted CA from file: /opt/graylog-agent/server-wildcard.crt
2015/09/30 08:53:32.203591 Connecting to [XX.XX.XX.XXX]:12210 (ServerName01)
2015/09/30 08:53:32.284243 Connected to XX.XX.XX.XXX
2015/09/30 08:53:47.284561 Read error looking for ack: read tcp XX.XX.XX.XXX:12210: i/o timeout
2015/09/30 08:53:47.284688 Setting trusted CA from file: /opt/graylog-agent/server-wildcard.crt
2015/09/30 08:53:47.287444 Connecting to [XX.XX.XX.XXX]:12210 (ServerName02)
2015/09/30 08:53:47.289371 Failure connecting to XX.XX.XX.XXX: dial tcp XX.XX.XX.XXX:12210: connection refused

**Comment by sivasamyk** [comment]
From the logs I see that you have 2 graylog servers configured. ServerName02 is not connected. ServerName01 is connected but not able to receive ack. Can you try the following options:

1) Make sure there is no firewall running in graylog server that blocks traffic outgoing on 5043 port (default port for input plugin)
2) Can you try with single graylog server in logstash-forwarder config (just to isolate the issue)
3) Increase timeout in logstash-forwarder config file

**Comment by rcord02** [comment]
Hi,
sorry for my late response, but had no time since now to have a look into this problem again.
Fortunately it has been solved just by changing the input from running on a single graylog node to run it as a global input. Configured as global input it's running fine. Thank you a lot for your help!
